## Numpy Array and basics


In [3]:
import numpy as np

### List VS NumPy Array

In [4]:
import time
st = time.time()
l = [i*i for i in range(1000000)]
print("List Time: " , time.time() - st)

start = time.time()
array = np.arange(1000000, dtype= np.int32)
print("NumPy array Time: " , time.time() - start)

List Time:  0.14089727401733398
NumPy array Time:  0.001966238021850586


### Creating NumPy Arrays

In [5]:
arr = np.array([[2,3,4,5],[6,7,8,3]])
print(arr)

[[2 3 4 5]
 [6 7 8 3]]


In [6]:
# zeros array
zero = np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Ones array
one = np.ones((4,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# creating an array with another array with constant number as its all entries
full = np.full((3,4),7,dtype=np.int32)
print(full)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
#creating array with random values 
random = np.random.random((4,5))  #generates random float numbers between 0.0 and 1.0
print(random)

[[0.15146978 0.32746882 0.70594323 0.92112721 0.14020021]
 [0.23022786 0.67493706 0.19895634 0.3428881  0.67175649]
 [0.04052088 0.22274518 0.63204245 0.26981931 0.84000105]
 [0.59861677 0.94314477 0.92079192 0.19428319 0.68353764]]


In [10]:
# sequence 
arr = np.arange(0,100,2, dtype=np.int32)
print("Sequence Array: \n", arr)

Sequence Array: 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


### Vector, Matrix and tensor

In [11]:
# 1D -> vector 
vector = np.array([2,3])
print(vector)

[2 3]


In [12]:
# 2D -> Matrix
matrix = np.array([[3,4,5],
                   [7,8,4]])
print(matrix)

[[3 4 5]
 [7 8 4]]


In [13]:
# 3D and 3D+ -> Tensor
Tensor = np.array([[[3,4,5],[5,8,0]],
                    [[0,9,1],[1,2,7]]])
print(Tensor)

[[[3 4 5]
  [5 8 0]]

 [[0 9 1]
  [1 2 7]]]


## Array Properties

In [40]:
# getting shape
arr = np.array([[2,3,4],
                 [5,6,7]])
print("Shape of Tensor: ", arr.shape)  #In general, all (1D, 2D and so on) are called Tensor
# getting Dimensions
print("Dimensions of Tensor: ", arr.ndim)
# getting size -> It tells total number of elements
print("Size of Tensor: ", arr.size)
# getting dtype (datatype)
print("Datatype of Tensor: ", arr.dtype)
# getting size per element in bytes_ here it is 8bytes bcz my PC is 64bit
print("Size per element in bytes: ", arr.itemsize)
# getting total size in bytes
print("Total size in Bytes of Tensor: ", arr.nbytes) # size (here it is 6) * itemsize (8 bytes per element) = 48 bytes 

Shape of Tensor:  (2, 3)
Dimensions of Tensor:  2
Size of Tensor:  6
Datatype of Tensor:  int64
Size per element in bytes:  8
Total size in Bytes of Tensor:  48


### Reshaping Array

In [41]:
org = np.arange(12)
print("Original Array: ", org)

reshaped = org.reshape((3,4))
print("Reshaped Array: \n", reshaped)

# Flattening array
flattened = reshaped.flatten()
print("Flattened Array: ", flattened)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Ravel()
##### It returns a "view", instead of copy
##### It also takes a multi-dimensional array and stretches it out into a single line of numbers

In [42]:
raveled = reshaped.ravel()
print("Raveled array: ", raveled)

Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Transpose

In [43]:
transpose = reshaped.T  #coverting rows into columns and columns into rows
print("transposed Matrix: \n", transpose)

transposed Matrix: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
